### ISSUE TITLE
RPC doesn't connect anymore

### ISSUE THREAD

**Issue by VeiTheOne** [greysdawn/pk-rpc#2]
Whenever I try and start it, I keep getting this error:
```js
Error: Could not connect
    at Socket.onerror (C:\Users\[Not giving my name out]\Desktop\pk-rpc-master\pk-rpc-master\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:520:26)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by selenated** [comment]
Hmm, looks like it's struggling to connect to your Discord client. Have you tried restarting Discord or your computer?

**Comment by VeiTheOne** [comment]
Nothing changed on a Clientrestart, and a Re-download.

**Comment by selenated** [comment]
Not really sure what else to do then 😅

As long as you're running the desktop client (not browser version) for Discord on the same machine as the RPC then it should be working- if it isn't then I'm not sure what we can do as that part of the code isn't ours

We're going on a trip for 4 days and will be away from our main computer, but once we get back we can try to take a look if it still isn't working by then?

**Comment by VeiTheOne** [comment]
It seemed to have reconnected itself. I wonder if the API issue that happened mid to late yesterday was the issue. SEVERAL bots were affected including PluralKit.

**Comment by selenated** [comment]
I'm actually not sure if that would be the issue- that part of the code isn't related to bots in general, but it's possible that whatever the issue was also stopped the client/API from recognizing rich presences

Either way, glad it's fixed now! Gonna go ahead and close this up
